import { v4 as uuidv4 } from "uuid";
import { CanvasObject } from "../types";

export const elements: CanvasObject[] = [
  {
    id: `screen-${uuidv4()}`,
    x: 250,
    y: 100,
    width: 400,
    height: 750,
    children: [
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "header",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                colSpan: 1,
                text: "Calves",
              },
            ],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 2,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            colSpan: 2,
            children: [
              {
                blockType: "input",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                placeholder: "Search calves...",
              },
            ],
          },
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 3,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "checkbox",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                colSpan: 2,
                label: "All",
              },
            ],
          },
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "checkbox",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                colSpan: 2,
                label: "Dead",
              },
            ],
          },
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "checkbox",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                colSpan: 2,
                label: "Pairout",
              },
            ],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "table",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
              },
            ],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 2,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "select",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
              },
            ],
          },
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "select",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
              },
            ],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 4,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "label",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                colSpan: 1,
                text: "Navigate somewhere in the app",
              },
            ],
            colSpan: 3,
          },
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "button",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                colSpan: 1,
                text: "Go ->",
              },
            ],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        colNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [],
          },
        ],
      },
    ],
    blockType: "screen",
  },
];
