import { v4 as uuidv4 } from "uuid";
import { CanvasBlock } from "../types";

export const elements: CanvasBlock[] = [
  {
    id: `screen-${uuidv4()}`,
    x: 250,
    y: 100,
    width: 400,
    height: 750,
    title: "Screen 1",
    style: {
      backgroundColor: "#EFE1D1",
    },
    children: [
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            columnSpan: 1,
            children: [
              {
                blockType: "header",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                text: "Loja",
                style: {
                  fontSize: 28,
                  textAlign: "center",
                },
              },
            ],
          },
        ],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            columnSpan: 1,
            children: [
              {
                blockType: "button",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                text: "Login",
                style: {
                  color: "white",
                  backgroundColor: "#331D2C",
                },
              },
            ],
          },
        ],
      },
    ],
    blockType: "screen",
  },
  {
    id: `screen-${uuidv4()}`,
    x: 750,
    y: 100,
    width: 400,
    height: 750,
    title: "Screen 2",
    style: {
      backgroundColor: "#EFE1D1",
    },
    children: [
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [],
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            columnSpan: 1,
            children: [
              {
                blockType: "header",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                text: "Login",
                style: {
                  fontSize: 32,
                },
              },
            ],
          },
        ],
        style: {
          backgroundColor: "white",
        },
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            columnSpan: 2,
            children: [
              {
                blockType: "input",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                placeholder: "Email",
              },
            ],
          },
        ],
        style: {
          backgroundColor: "white",
        },
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            columnSpan: 2,
            children: [
              {
                blockType: "input",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                placeholder: "Password",
              },
            ],
          },
        ],
        style: {
          backgroundColor: "white",
        },
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 2,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            columnSpan: 1,
            children: [],
          },
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            columnSpan: 1,
            children: [
              {
                blockType: "label",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                text: "Forgot Password?",
                style: {
                  width: "100%",
                  fontSize: 17,
                  fontWeight: "bold",
                  display: "inline-block",
                  textAlign: "right",
                },
              },
            ],
          },
        ],
        style: {
          backgroundColor: "white",
        },
      },
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 75,
        columnNumber: 1,
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            columnSpan: 1,
            children: [
              {
                blockType: "button",
                id: `block-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 200,
                height: 50,
                children: [],
                text: "Continue",
                style: {
                  color: "white",
                  backgroundColor: "#331D2C",
                },
              },
            ],
          },
        ],
        style: {
          backgroundColor: "white",
        },
      },
    ],
    blockType: "screen",
  },
  {
    id: `screen-${uuidv4()}`,
    x: 250,
    y: 950,
    width: 1024,
    height: 750,
    title: "Screen 3",
    style: {
      backgroundColor: "rgb(238, 238, 238)",
    },
    children: [
      {
        blockType: "grid-row",
        id: `grid-row-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 500,
        columnNumber: 12,
        style: {
          padding: 0,
        },
        children: [
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            columnSpan: 3,
            children: [
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 50,
                columnNumber: 1,
                style: {
                  alignItems: "center",
                },
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 1,
                    children: [
                      {
                        blockType: "header",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 200,
                        height: 50,
                        children: [],
                        text: "Agri Dealer",
                        style: {
                          fontSize: 28,
                          color: "white",
                          textAlign: "center",
                        },
                      },
                    ],
                  },
                ],
              },
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 50,
                columnNumber: 1,
                style: {
                  alignItems: "center",
                  borderTop: "1px solid white",
                  borderBottom: "1px solid white",
                },
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 1,
                    children: [
                      {
                        blockType: "header",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 200,
                        height: 50,
                        children: [],
                        text: "Loja",
                        style: {
                          fontSize: 28,
                          color: "white",
                          textAlign: "center",
                        },
                      },
                    ],
                  },
                ],
              },
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 50,
                columnNumber: 1,
                style: {
                  alignItems: "center",
                },
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 1,
                    children: [
                      {
                        blockType: "icon",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 50,
                        height: 50,
                        children: [],
                      },
                      {
                        blockType: "header",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 200,
                        height: 50,
                        children: [],
                        text: "Bayer Dealer Bucket",
                        style: {
                          fontSize: 20,
                          color: "white",
                          textAlign: "left",
                        },
                      },
                    ],
                  },
                ],
              },
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 50,
                columnNumber: 1,
                style: {
                  alignItems: "center",
                  borderRadius: "3px",
                  backgroundColor: "#4caf50",
                },
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 1,
                    children: [
                      {
                        blockType: "icon",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 50,
                        height: 50,
                        children: [],
                      },
                      {
                        blockType: "header",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 200,
                        height: 50,
                        children: [],
                        text: "Customers",
                        style: {
                          fontSize: 20,
                          color: "white",
                          textAlign: "left",
                        },
                      },
                    ],
                  },
                ],
              },
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 50,
                columnNumber: 1,
                style: {
                  alignItems: "center",
                },
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 1,
                    children: [
                      {
                        blockType: "header",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 200,
                        height: 50,
                        children: [],
                        text: "Inventory",
                        style: {
                          fontSize: 20,
                          color: "white",
                          textAlign: "left",
                        },
                      },
                    ],
                  },
                ],
              },
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 50,
                columnNumber: 1,
                style: {
                  alignItems: "center",
                },
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 1,
                    children: [
                      {
                        blockType: "header",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 200,
                        height: 50,
                        children: [],
                        text: "Reports",
                        style: {
                          fontSize: 20,
                          color: "white",
                          textAlign: "left",
                        },
                      },
                    ],
                  },
                ],
              },
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 50,
                columnNumber: 1,
                style: {
                  alignItems: "center",
                },
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 1,
                    children: [
                      {
                        blockType: "header",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 200,
                        height: 50,
                        children: [],
                        text: "Settings",
                        style: {
                          fontSize: 20,
                          color: "white",
                          textAlign: "left",
                        },
                      },
                    ],
                  },
                ],
              },
            ],
            style: {
              display: "flex",
              padding: "10px",
              backgroundColor: "black",
              flexDirection: "column",
            },
          },
          {
            blockType: "grid-column",
            id: `grid-column-${uuidv4()}`,
            x: 0,
            y: 0,
            width: 200,
            height: 250,
            children: [
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 75,
                columnNumber: 12,
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 7,
                    children: [
                      {
                        blockType: "header",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 200,
                        height: 50,
                        children: [],
                        text: "Customers",
                        style: {
                          fontSize: 24,
                          fontWeight: 600,
                          textAlign: "left",
                          color: "rgb(60, 72, 88)",
                        },
                      },
                    ],
                  },
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 5,
                    children: [
                      {
                        blockType: "grid-row",
                        id: `grid-row-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 400,
                        height: 75,
                        columnNumber: 6,
                        children: [
                          {
                            blockType: "grid-column",
                            id: `grid-column-${uuidv4()}`,
                            x: 0,
                            y: 0,
                            width: 200,
                            height: 250,
                            columnSpan: 4,
                            children: [
                              {
                                blockType: "input",
                                id: `block-${uuidv4()}`,
                                x: 0,
                                y: 0,
                                width: 200,
                                height: 50,
                                children: [],
                                placeholder: "Searchbar",
                                style: {
                                  border: "none",
                                  borderRadius: 0,
                                  backgroundColor: "transparent",
                                  borderBottom: "1px solid rgb(60, 72, 88)",
                                },
                              },
                            ],
                          },
                          {
                            blockType: "grid-column",
                            id: `grid-column-${uuidv4()}`,
                            x: 0,
                            y: 0,
                            width: 200,
                            height: 250,
                            columnSpan: 2,
                            children: [
                              {
                                blockType: "button",
                                id: `block-${uuidv4()}`,
                                x: 0,
                                y: 0,
                                width: 200,
                                height: 50,
                                children: [],
                                text: "Add New",
                                style: {
                                  color: "white",
                                  border: "none",
                                  borderRadius: 5,
                                  backgroundColor: "#4caf50",
                                },
                              },
                            ],
                          },
                        ],
                        style: {
                          gap: 10,
                        },
                      },
                    ],
                  },
                ],
                style: {
                  alignItems: "center",
                },
              },
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 550,
                columnNumber: 1,
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 200,
                    height: 250,
                    columnSpan: 1,
                    children: [
                      {
                        blockType: "table",
                        id: `block-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 200,
                        height: 50,
                        children: [],
                        style: {
                          padding: 5,
                          border: "none",
                          borderRadius: 5,
                          backgroundColor: "white",
                          boxShadow: "rgba(0, 0, 0, 0.14) 0px 1px 4px 0px",
                        },
                        tableConfig: {
                          data: [
                            [
                              "Dan L Brick",
                              "Create quote",
                              "PO#1314497 (ADV)",
                              "$0.00",
                            ],
                            [
                              "Dev Rahul",
                              "Create quote",
                              "PO#1314497 (ADV)",
                              "$958,627.06",
                            ],
                          ],
                          columns: [
                            "Customer",
                            "Quotes",
                            "Purchase Orders",
                            "Grower Balance Due",
                          ],
                        },
                      },
                    ],
                  },
                ],
                style: {
                  alignItems: "center",
                  alignContent: "flex-start",
                },
              },
              {
                blockType: "grid-row",
                id: `grid-row-${uuidv4()}`,
                x: 0,
                y: 0,
                width: 400,
                height: 100,
                columnNumber: 1,
                children: [
                  {
                    blockType: "grid-column",
                    id: `grid-column-${uuidv4()}`,
                    x: 0,
                    y: 0,
                    width: 400,
                    height: 650,
                    columnSpan: 1,
                    children: [
                      {
                        blockType: "pagination",
                        id: `pagination-${uuidv4()}`,
                        x: 0,
                        y: 0,
                        width: 400,
                        height: 50,
                        children: [],
                      },
                    ],
                  },
                ],
              },
            ],
            columnSpan: 9,
            style: {
              alignItems: "center",
            },
          },
        ],
      },
    ],
    blockType: "screen",
  },
  {
    id: `screen-${uuidv4()}`,
    x: 750,
    y: 100,
    width: 400,
    height: 750,
    title: "Screen 4",
    style: {
      padding: "12px",
      backgroundColor: "rgba(242, 244, 254, 1)",
    },
    children: [
      {
        blockType: "advanced-card-list",
        id: `block-${uuidv4()}`,
        x: 0,
        y: 0,
        width: 400,
        height: 750,
        children: [],
        data: [
          {
            name: "Kristian Brown",
            isPostcardList: true,
          },
          {
            name: "Ann Smith",
            phoneNumber: "+380462918462",
            address: "1234 Elm Street, Apt 56B, Springfield, IL 62704",
            isPostcardList: true,
          },
          {
            name: "Tim Cooper",
            phoneNumber: "+380462918462",
            address: "1234 Elm Street, Apt 56B, Springfield, IL 62704",
            isPostcardList: true,
          },
        ],
      },
    ],
    blockType: "screen",
  },
];
