import { v4 as uuidv4 } from "uuid";
import { CanvasObject } from "../types";

export const elements: CanvasObject[] = [
  {
    id: `screen-${uuidv4()}`,
    x: 250,
    y: 100,
    width: 1024,
    height: 750,
    title: "Screen 1",
    style: {
      backgroundColor: "#EFE1D1",
    },
    children: [],
    blockType: "screen",
  },
  // {
  //   id: `screen-${uuidv4()}`,
  //   x: 250,
  //   y: 100,
  //   width: 400,
  //   height: 750,
  //   title: "Screen 1",
  //   style: {
  //     backgroundColor: "#EFE1D1",
  //   },
  //   children: [
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           children: [
  //             {
  //               blockType: "header",
  //               id: `block-${uuidv4()}`,
  //               x: 0,
  //               y: 0,
  //               width: 200,
  //               height: 50,
  //               children: [],
  //               colSpan: 1,
  //               text: "Loja",
  //               style: {
  //                 fontSize: 28,
  //                 textAlign: "center",
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           children: [
  //             {
  //               blockType: "button",
  //               id: `block-${uuidv4()}`,
  //               x: 0,
  //               y: 0,
  //               width: 200,
  //               height: 50,
  //               children: [],
  //               colSpan: 1,
  //               text: "Login",
  //               style: {
  //                 color: "white",
  //                 backgroundColor: "#331D2C",
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //   ],
  //   blockType: "screen",
  // },
  // {
  //   id: `screen-${uuidv4()}`,
  //   x: 750,
  //   y: 100,
  //   width: 400,
  //   height: 750,
  //   title: "Screen 2",
  //   style: {
  //     backgroundColor: "#EFE1D1",
  //   },
  //   children: [
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [],
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           children: [
  //             {
  //               blockType: "header",
  //               id: `block-${uuidv4()}`,
  //               x: 0,
  //               y: 0,
  //               width: 200,
  //               height: 50,
  //               children: [],
  //               colSpan: 1,
  //               text: "Login",
  //               style: {
  //                 fontSize: 32,
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //       style: {
  //         backgroundColor: "white",
  //       },
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           colSpan: 2,
  //           children: [
  //             {
  //               blockType: "input",
  //               id: `block-${uuidv4()}`,
  //               x: 0,
  //               y: 0,
  //               width: 200,
  //               height: 50,
  //               children: [],
  //               placeholder: "Email",
  //             },
  //           ],
  //         },
  //       ],
  //       style: {
  //         backgroundColor: "white",
  //       },
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           colSpan: 2,
  //           children: [
  //             {
  //               blockType: "input",
  //               id: `block-${uuidv4()}`,
  //               x: 0,
  //               y: 0,
  //               width: 200,
  //               height: 50,
  //               children: [],
  //               placeholder: "Password",
  //             },
  //           ],
  //         },
  //       ],
  //       style: {
  //         backgroundColor: "white",
  //       },
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 2,
  //       children: [
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           colSpan: 1,
  //           children: [],
  //         },
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           colSpan: 1,
  //           children: [
  //             {
  //               blockType: "label",
  //               id: `block-${uuidv4()}`,
  //               x: 0,
  //               y: 0,
  //               width: 200,
  //               height: 50,
  //               children: [],
  //               colSpan: 1,
  //               text: "Forgot Password?",
  //               style: {
  //                 width: "100%",
  //                 fontSize: 17,
  //                 fontWeight: "bold",
  //                 display: "inline-block",
  //                 textAlign: "right",
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //       style: {
  //         backgroundColor: "white",
  //       },
  //     },
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 75,
  //       colNumber: 1,
  //       children: [
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           children: [
  //             {
  //               blockType: "button",
  //               id: `block-${uuidv4()}`,
  //               x: 0,
  //               y: 0,
  //               width: 200,
  //               height: 50,
  //               children: [],
  //               colSpan: 1,
  //               text: "Continue",
  //               style: {
  //                 color: "white",
  //                 backgroundColor: "#331D2C",
  //               },
  //             },
  //           ],
  //         },
  //       ],
  //       style: {
  //         backgroundColor: "white",
  //       },
  //     },
  //   ],
  //   blockType: "screen",
  // },
  // {
  //   id: `screen-${uuidv4()}`,
  //   x: 250,
  //   y: 950,
  //   width: 1024,
  //   height: 750,
  //   title: "Screen 3",
  //   style: {
  //     backgroundColor: "#EFE1D1",
  //   },
  //   children: [
  //     {
  //       blockType: "grid-row",
  //       id: `grid-row-${uuidv4()}`,
  //       x: 0,
  //       y: 0,
  //       width: 400,
  //       height: 750,
  //       colNumber: 6,
  //       children: [
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           children: [
  //             {
  //               blockType: "header",
  //               id: `block-${uuidv4()}`,
  //               x: 0,
  //               y: 0,
  //               width: 200,
  //               height: 50,
  //               children: [],
  //               colSpan: 1,
  //               text: "Loja",
  //               style: {
  //                 fontSize: 32,
  //                 textAlign: "center",
  //               },
  //             },
  //           ],
  //           colSpan: 3,
  //           style: {
  //             display: "flex",
  //             justifyContent: "center",
  //           },
  //         },
  //         {
  //           blockType: "grid-column",
  //           id: `grid-column-${uuidv4()}`,
  //           x: 0,
  //           y: 0,
  //           width: 200,
  //           height: 250,
  //           children: [
  //             {
  //               blockType: "grid-row",
  //               id: `grid-row-${uuidv4()}`,
  //               x: 0,
  //               y: 0,
  //               width: 400,
  //               height: 75,
  //               colNumber: 2,
  //               children: [
  //                 {
  //                   blockType: "grid-column",
  //                   id: `grid-column-${uuidv4()}`,
  //                   x: 0,
  //                   y: 0,
  //                   width: 200,
  //                   height: 250,
  //                   colSpan: 1,
  //                   children: [
  //                     {
  //                       blockType: "header",
  //                       id: `block-${uuidv4()}`,
  //                       x: 0,
  //                       y: 0,
  //                       width: 200,
  //                       height: 50,
  //                       children: [],
  //                       colSpan: 1,
  //                       text: "Loja",
  //                       style: {
  //                         fontSize: 18,
  //                         textAlign: "center",
  //                       },
  //                     },
  //                   ],
  //                 },
  //                 {
  //                   blockType: "grid-column",
  //                   id: `grid-column-${uuidv4()}`,
  //                   x: 0,
  //                   y: 0,
  //                   width: 200,
  //                   height: 250,
  //                   colSpan: 1,
  //                   children: [],
  //                 },
  //               ],
  //             },
  //           ],
  //           colSpan: 3,
  //           style: {
  //             backgroundColor: "white",
  //           },
  //         },
  //       ],
  //     },
  //   ],
  //   blockType: "screen",
  // },
];
